[0;1;32m‚óè[0m mariadb.service - MariaDB 10.3.39 database server
     Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
     Active: [0;1;32mactive (running)[0m since Wed 2025-04-02 11:53:05 CEST; 2h 59min ago
       Docs: man:mysqld(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 845 (mysqld)
     Status: "Taking your SQL requests now..."
      Tasks: 31 (limit: 9381)
     Memory: 98.4M
     CGroup: /system.slice/mariadb.service
             ‚îî‚îÄ845 /usr/sbin/mysqld

avril 02 11:53:03 66def77e45e304d0d352b426.cloud.eddi.xyz systemd[1]: Starting MariaDB 10.3.39 database server...
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz systemd[1]: Started MariaDB 10.3.39 database server.
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1046]: Upgrading MySQL tables if necessary.
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1049]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mLooking for 'mysql' as: /usr/bin/mysql[0m
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1049]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mReading datadir from the MariaDB server failed. Got the following error when executing the 'mysql' command line client[0m
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1049]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)[0m
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1049]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mFATAL ERROR: Upgrade failed[0m
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz /etc/mysql/debian-start[1060]: Checking for insecure root accounts.
avril 02 11:53:05 66def77e45e304d0d352b426.cloud.eddi.xyz debian-start[1063]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
